### ISSUE TITLE
CRC32 reset

### ISSUE THREAD

**Issue by paleolitico** [astei/libdeflate-java#3]
I think [this](https://github.com/astei/libdeflate-java/blob/5677ce2d6bd09b10f6d3a0063fc7826da54fe783/libdeflate-java-core/src/main/java/me/steinborn/libdeflate/LibdeflateCRC32.java#L60) should be `crc32 = 0` rather than `crc32 = 1`.

**Comment by astei** [comment]
Thanks for the catch - will fix it.
