### ISSUE TITLE
Problem with JNI code

### ISSUE THREAD

**Issue by n9tank** [astei/libdeflate-java#7]
使用JNI操作堆会崩溃。
Manipulating the heap with JNI crashes.
我修复了它。
I fixed it.
https://github.com/n9tank/libDeflate-android

**Comment by astei** [comment]
The only bug I see is that there was a typo in a `ReleasePrimitiveArrayCritical` call for the "both buffers are heap buffers" case, so I corrected just that issue. Everything else you did is a net degradation of functionality. For instance, there is the possibility that we might have support for a library that does permit buffer sizes much larger than those Java permits by default, and the native bindings reflect that.

**Comment by n9tank** [comment]
这些不是我考虑的，Frok的分支只是给我自己在用。
That's not what I'm thinking about. Frok's branch is just for my own use.
